apiVersion: v1
kind: Endpoints
metadata:
  labels:
    nodes: mysql-exporter
  name: mysql-exporter
  namespace: monitoring
subsets:
  - addresses:
      - ip: "172.17.207.18"
        nodeName: mysql-s2
    ports:
      - name: nodexp
        port: 9104
        protocol: TCP


---
apiVersion: v1
kind: Service
metadata:
  labels:
    nodes: mysql-exporter
  name: mysql-exporter
  namespace: monitoring
spec:
  clusterIP: None
  ports:
    - name: nodexp
      port: 9104
      protocol: TCP
      targetPort: 9104
  selector:
    nodes: mysql-exporter
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}

---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    prometheus: k8s
  name: mysql-exporter
  namespace: monitoring
spec:
  endpoints:
    - interval: 30s
      port: nodexp
  jobLabel: nodes
  namespaceSelector:
    matchNames:
      - monitoring
  selector:
    matchLabels:
      nodes: mysql-exporter