apiVersion: v1
kind: Endpoints
metadata:
  labels:
    nodes: rocketmq-exporter
  name: rocketmq-exporter
  namespace: monitoring
subsets:
  - addresses:
      - ip: "172.17.207.18"
        nodeName: rocketmq-s2
    ports:
      - name: rocketmqport
        port: 9107
        protocol: TCP


---
apiVersion: v1
kind: Service
metadata:
  labels:
    nodes: rocketmq-exporter
  name: rocketmq-exporter
  namespace: monitoring
spec:
  clusterIP: None
  ports:
    - name: rocketmqport
      port: 9107
      protocol: TCP
      targetPort: 9107
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}

---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    prometheus: k8s
  name: rocketmq-exporter
  namespace: monitoring
spec:
  endpoints:
    - interval: 30s
      port: rocketmqport
  jobLabel: nodes
  namespaceSelector:
    matchNames:
      - monitoring
  selector:
    matchLabels:
      nodes: rocketmq-exporter